name: Test Fabric Data Pipelines
on: workflow_dispatch
jobs:
  test-dp:
    name: Test Data Pipeline
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses:  actions/checkout@v4

      - name: Use Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Necessary libraries
        shell: pwsh
        run: |
          pip install data-factory-testing-framework
          pip install pytest

      - name: Run sample pipeline test
        shell: pwsh
        run: |
          pytest fabric-tests-examples/kchant-simple-data-pipeline-tests.py --junitxml=simple-pipeline-test-results.xml

      - name: Upload Pipeline Test Results
        uses: actions/upload-artifact@v4
        with:
          name: simple-pipeline-test-Results
          path: '**.simple-*.xml'

